### ISSUE TITLE
Epic : WMS 8022 : TEQ in Oracle Database v2.0

### ISSUE THREAD

**Issue by pasimoes** [oracle/microservices-datadriven#418]
Summary of new features:

- [ ] #443 
- [ ] TEQ Observability : Performance metrics in Prometheus/Grafana
- [ ] Multiple Shards/Consumers - Kafka JMS Source/Sink Connectors for multiple partitions of a topic
- [ ] UI Interface - show common features of TEQ with an easy to use front-end browser interface
