### ISSUE TITLE
Spring boot work

### ISSUE THREAD

**Issue by paulparkinson** [oracle/microservices-datadriven#431]
- [x] #430 : Add extended AQ/TEQ messaging support in spring boot
 - [x] #429 : Add oracle json support to spring (and mn) data
 - [x] #428 : Add okafka support in spring boot

**Comment by andytael** [comment]
I believe all is done
